version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: some-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbPersonel
      MYSQL_USER: burak
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  my-db-data:
    driver: local

networks:
  my-network:
    driver: bridge